# Generated by Django 4.2.5 on 2023-10-23 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_category_image_order_is_piece_order_monnaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=13, unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('nationalite', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('photo_livreur', models.ImageField(upload_to='dossier_livreurs/photo/%Y/%m/%d')),
                ('permis_recto', models.ImageField(upload_to='dossier_livreurs/permis/%Y/%m/%d')),
                ('permis_verso', models.ImageField(upload_to='dossier_livreurs/permis/%Y/%m/%d')),
                ('carte_grise_recto', models.ImageField(upload_to='dossier_livreurs/carte_grise/%Y/%m/%d')),
                ('carte_grise_verso', models.ImageField(upload_to='dossier_livreurs/carte_grise/%Y/%m/%d')),
                ('assurance', models.ImageField(upload_to='dossier_livreurs/assurance/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livreurs.dossierlivreur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
