# Generated by Django 4.2.5 on 2023-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossierlivreur',
            old_name='prenom',
            new_name='prenoms',
        ),
        migrations.AddField(
            model_name='dossierlivreur',
            name='is_valid',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
