# Generated by Django 4.2.5 on 2023-10-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0002_rename_prenom_dossierlivreur_prenoms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livreur',
        ),
    ]
