# Generated by Django 4.2.5 on 2023-10-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0004_livreur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livreur',
        ),
    ]
