# Generated by Django 4.2.5 on 2023-10-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_order_waiting_order_created_at_order_status'),
        ('livreurs', '0006_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='commande',
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('livreur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livreurs.livreur')),
            ],
        ),
    ]
