# Generated by Django 4.2.5 on 2023-10-31 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0007_remove_livreur_commande_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierlivreur',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 15, 30, 45, 377422, tzinfo=datetime.timezone.utc)),
        ),
    ]
