# Generated by Django 4.2.5 on 2023-10-31 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0008_dossierlivreur_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierlivreur',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 15, 39, 39, 240492, tzinfo=datetime.timezone.utc)),
        ),
    ]
