# Generated by Django 4.2.5 on 2023-10-31 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0009_alter_dossierlivreur_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierlivreur',
            name='refuser',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='dossierlivreur',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 17, 22, 48, 185164, tzinfo=datetime.timezone.utc)),
        ),
    ]
