# Generated by Django 4.2.5 on 2023-11-01 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0011_livreur_activity_alter_dossierlivreur_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierlivreur',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
