# Generated by Django 4.2.5 on 2023-11-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0012_alter_dossierlivreur_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='statut',
            new_name='status',
        ),
    ]
