# Generated by Django 4.2.5 on 2023-11-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0013_rename_statut_livraison_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='commande',
            new_name='order',
        ),
    ]
