# Generated by Django 4.2.5 on 2023-11-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0015_livreur_livraison_count_livreur_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livreurs.livreur'),
        ),
    ]
