# Generated by Django 4.2.5 on 2023-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_meal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0, help_text='Temps de préparation en minutes'),
        ),
    ]
