# Generated by Django 4.2.5 on 2023-09-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
