# Generated by Django 4.2.5 on 2023-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_order_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_piece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='monnaie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
