# Generated by Django 4.2.5 on 2023-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_category_image_order_is_piece_order_monnaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiting',
            field=models.BooleanField(default=True),
        ),
    ]
