# Generated by Django 4.2.5 on 2023-10-27 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_order_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiting',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de préparation'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
