# Generated by Django 4.2.5 on 2023-10-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_order_waiting_order_created_at_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_cook',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
