# Generated by Django 4.2.5 on 2023-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_cartitem_user_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
