# Generated by Django 4.2.5 on 2023-10-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_cartitem_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='second_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
