# Generated by Django 4.2.5 on 2023-11-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_meal_second_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code promotionnel unique', max_length=20, unique=True)),
                ('description', models.TextField(help_text='Description du code promotionnel', max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Pourcentage'), ('amount', 'Montant fixe')], default='percent', help_text='Type de réduction (pourcentage ou montant fixe)', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Montant de la réduction en pourcentage (0-100) ou montant fixe', max_digits=5)),
                ('start_date', models.DateTimeField(help_text='Date de début de validité du code promotionnel')),
                ('end_date', models.DateTimeField(help_text='Date de fin de validité du code promotionnel')),
                ('active', models.BooleanField(default=True, help_text='Code promotionnel actif ou inactif')),
            ],
        ),
    ]
