# Generated by Django 4.2.5 on 2023-11-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=False, help_text='Code promotionnel actif ou inactif'),
        ),
    ]
