# Generated by Django 4.2.5 on 2023-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_promocode_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Pourcentage'), ('amount', 'Montant fixe')], default='percent', help_text='Type de réduction (pourcentage ou montant fixe)', max_length=60),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la réduction en pourcentage (0-100) ou montant fixe', max_digits=7),
        ),
    ]
