# Generated by Django 4.2.5 on 2023-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_promocode_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
