# Generated by Django 4.2.5 on 2023-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_meal_is_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='second_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
