# Generated by Django 4.2.5 on 2023-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_meal_second_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, help_text='Code promotionnel actif ou inactif'),
        ),
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.TimeField(blank=True, help_text='Date de fin de validité du code promotionnel', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_date',
            field=models.TimeField(blank=True, help_text='Date de début de validité du code promotionnel', null=True),
        ),
    ]
