# Generated by Django 4.2.5 on 2023-11-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_category_active_category_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
