# Generated by Django 4.2.7 on 2023-11-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
