# Generated by Django 4.2.7 on 2024-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de préparation'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('recuperer', 'Récupérée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
